team_number = int(input("What is the team number?"))
print(team_number)
team_name = input("What is the team name?")
print(team_name)
location = input("Where is the team located?")
print(location)
rookie_year = int(input("What year was the team started?"))
print(rookie_year)
is_active = input("Is the team stil active?")
print(team_number)
print(team_name)
print(location)
print(rookie_year)
print(is_active)